import {StyleSheet, Platform} from 'react-native';
import {Colors} from '../../../styles';
import {getDimensions} from '../../../services/DimensionsManager';

export default StyleSheet.create({
  mapContainerStyle: {
    position: 'absolute',
    width: getDimensions().width,
    height: getDimensions().height,
  },
  markerBackgroundImageStyle: {
    width: 60,
    height: 66,
    top: Platform.OS == 'ios' ? -33 : 0,
  },
  currentMarkerContainerStyle: {
    width: 46,
    borderRadius: 23,
    height: 46,
    backgroundColor: Colors.whiteWithOpacity(0.4),
    justifyContent: 'center',
    alignItems: 'center',
  },
  currentMarkerViewStyle: {
    width: 36,
    borderRadius: 18,
    height: 36,
    backgroundColor: Colors.denimBlue,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchTextInputStyle: {
    marginLeft: 15,
    top: Platform.OS == 'ios' ? -2 : 0,
    fontSize: 16,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: -0.39,
  },
  markerBackgroundImageInputStyle: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    width: 45,
    height: 45,
    borderRadius: 22,
    marginLeft: 8,
    marginTop: 8,
    backgroundColor: Colors.denimBlue,
    shadowColor: 'rgba(64, 80, 164, 0.35)',
    shadowOffset: {
      width: 0,
      height: 14,
    },
    shadowRadius: 32,
    shadowOpacity: 1,
    top: Platform.OS == 'android' ? 0 : -33,
  },
  containerStyle: {
    flex: 1,
  },
  markerViewStyle: {
    width: 6,
    height: 6,
    backgroundColor: Colors.denimBlue,
    borderRadius: 3,
    top: Platform.OS == 'ios' ? -33 : 0,
    left: 27,
  },
  markerContainerStyle: {
    borderRadius: 33,
    width: 66,
    height: 66,
    backgroundColor: Colors.whiteWithOpacity(0.4),
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rightImagesStyle: {
    width: 14,
    height: 14,
  },
  backImageStyle: {
    width: 37,
    height: 37,
  },
  searchViewStyle: {
    top: 40,
    flexDirection: 'row',
  },
  currentLocationButton: {
    top: 86,
  },
  circleViewStyle: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    right: 20,
    width: 36,
    borderRadius: 18,
    height: 36,
    backgroundColor: Colors.white,
  },
  resetValuesStyle: {
    marginBottom: 14,
  },
  resetValuesTextStyle: {
    fontSize: 13,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: -0.31,
    color: Colors.denimBlue,
  },
  applyButtonStyle: {
    width: getDimensions().width - 40,
    marginTop: 50,
    marginBottom: 14,
  },
  coordinatesStyle: {
    fontSize: 15,
    fontWeight: 'normal',
    fontStyle: 'normal',
    lineHeight: 22,
    letterSpacing: -0.36,
    color: Colors.lightBlueGrey,
    marginBottom: 7,
    width: getDimensions().width - 40,
  },
  separatorViewStyle: {
    width: 335,
    height: 1,
    backgroundColor: Colors.lightBlueGreyTwo,
  },
  coordinatesTextStyle: {
    width: getDimensions().width - 40,
    marginTop: 30,
    marginBottom: 3,
    fontSize: 15,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: 20,
    letterSpacing: -0.24,
    color: Colors.dusk,
  },
  bottomTextStyle: {
    width: 287,
    fontSize: 15,
    marginTop: 30,
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.36,
    textAlign: 'center',
    color: Colors.lightBlueGrey,
    marginBottom: 30,
  },
  arrowStyle: {
    width: 36,
    height: 3.5,
    marginTop: 6,
    borderRadius: 100,
    backgroundColor: Colors.lightPeriwinkle30,
  },
  backImageContainerStyle: {
    position: 'absolute',
    left: 20,
    top: 40,
  },
  bottomContainerViewStyle: {
    alignItems: 'center',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: Colors.white,
  },
});
